### ISSUE TITLE
Downloading from vandaldata.polito.it

### ISSUE THREAD

**Issue by bchidlovskii** [gmberton/MeshVPR#1]
Hi,
Thank you for the great code and datasets !
However, it seems rsync can not connect to host vandaldata.polito.it to download the dataset sample.
Thank you

**Comment by gmberton** [comment]
Hi, can you share a screenshot of your terminal so that I can see what the problem is? I am able to download the dataset simply like this, also on servers on different continents.
`rsync -rhz --info=progress2 --ignore-existing rsync://vandaldata.polito.it/sf_xl/mesh_vpr_datasets/test_sets/val_set .`

**Comment by bchidlovskii** [comment]
Hi, 
Thank for the quick answer.
Here is the screenshot.

![image](https://github.com/gmberton/MeshVPR/assets/77396823/f2d42075-78e9-471f-9010-75ba2ca53a2e)

The same for nc:
(base) [chidlovs@sensei ~]$ nc -zv 130.192.40.100 22
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection timed out.

We have a firewall but from our server we can http/ssh/rsync .
You have mentioned remote servers, does any of them set a firewall ?
Thank you 
PS> I ll check on out side as well

**Comment by bchidlovskii** [comment]
After verification, the problem was on our side, with rsync parameters .
Sorry for misleading message.
and thank you again

**Comment by gmberton** [comment]
No worries, I hope MeshVPR can be helpful for your goals :)
